package com.dmitry.yume.domain.models

data class AnimeDetailed(
    val id: Int,
    val title: String?,
    val titleEn: String?,
    val posterUrl: String?,
    val year: Int?,
    val rating: Double?,
    val hasKodik: Boolean = false,
    val hasLibria: Boolean = false,
    val status: String? = null,
    val favorite: Boolean = false,
    val score: Int? = null,
    val isAvailable: Boolean,
    val description: String?,
    val duration: Int?,
    val genres: List<String>?,
    val studios: List<String>?,
    val relations: List<Anime>,
    val kind: String? = null,
    val releaseStatus: String? = null,
    val ratingSource: String? = null,
    val ageRating: String? = null,
    val episodesTotal: Int? = null,
    val episodesAvailable: Int? = null,
    val airedOn: String? = null,
    val airedOnPrecision: String? = null,
    val releasedOn: String? = null,
    val releasedOnPrecision: String? = null,
    val nextEpisodeAt: String? = null,
    val lastEpisodeNumber: Int? = null
)
